export { }

describe("Address Registry Tests", () => {
    beforeEach(() => {
        cy.visit("http://localhost:3000")
        cy.get('#emailAddress').type("bipepek652@slvlog.com")
        cy.get('#password').type("AdairBenjamin2008$")
        cy.get('.btn-primary').click()
        cy.get('[href="/providers"] > .flex').click()
    })

    it("Should display new address form", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('.bg-yellow-500').click()
        cy.get('.rounded-lg > .font-bold').should("contain.text", "Añadir dirección")
    })

    it("Should display 'Campo obligatorio' in outdoor number field", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('.bg-yellow-500').click()
        cy.get('#outdoorNumber').focus()        
        cy.get('#indoorNumber').focus()        
        cy.get('.input-error-text').should("contain.text", "Campo obligatorio")
    })

    it("Should display 'Por favor ingrese 50 o menos caracteres' in outdoor number field", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('.bg-yellow-500').click()
        cy.get('#outdoorNumber').type("123456789012345678901234567890123456789012345678901")
        cy.get('.btn-primary').click()
        cy.get('.input-error-text').should("contain.text", "Por favor ingrese 50 o menos caracteres")
    })

    it("Should display 'Por favor ingrese 50 o menos caracteres' in indoor number field", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('.bg-yellow-500').click()
        cy.get('#indoorNumber').type("123456789012345678901234567890123456789012345678901")
        cy.get('.btn-primary').click()
        cy.get('.input-error-text').should("contain.text", "Por favor ingrese 50 o menos caracteres")
    })
    
    it("Should display 'Campo obligatorio' in street field", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('.bg-yellow-500').click()
        cy.get('#street').type("    ")
        cy.get('.btn-primary').click()
        cy.get('.input-error-text').should("contain.text", "Campo obligatorio")
    })

    it("Should display 'Por favor ingrese 100 o menos caracteres' in street field", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('.bg-yellow-500').click()
        cy.get('#street').type("abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghija")
        cy.get('.btn-primary').click()
        cy.get('.input-error-text').should("contain.text", "Por favor ingrese 100 o menos caracteres")
    })

    it("Should display 'Por favor ingrese 100 o menos caracteres' in suburb field", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('.bg-yellow-500').click()
        cy.get('#suburb').type("abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghija")
        cy.get('.btn-primary').click()
        cy.get('.input-error-text').should("contain.text", "Por favor ingrese 100 o menos caracteres")
    })

    it("Should display 'Campo obligatorio' in city field of the new address form", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('.bg-yellow-500').click()
        cy.get('#cityId').focus()   
        cy.get('#street').type("calle 1")
        cy.get('.input-error-text').should("contain.text", "Campo obligatorio")                
    })

    it("Should register new address successfully", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('.bg-yellow-500').click()
        cy.get('#outdoorNumber').type("5")
        cy.get('#street').type("Av. José Vasconcelos")
        cy.get('#suburb').type("Los manantiales")
        cy.get('#cityId').select("Coatepec")
        cy.get('.btn-primary').click()
        cy.get('.rounded-md > .font-bold').should("contain.text", "Dirección registrada")
    })
})