export {}

describe("Price Rate Registration Tests", () => {
    beforeEach(() => {        
        cy.visit("http://localhost:3000")
        cy.get('#emailAddress').type("bipepek125@slvlog.com")
        cy.get('#password').type("AdairBenjamin2008$")
        cy.get('.btn-primary').click()
    })

    it("Should register a new price rate for drug purchase", () => {
        cy.get('.bg-yellow-500').click()        
        cy.get('#monday').check({force: true})
        cy.get('#tuesday').check({force: true})
        cy.get('#wednesday').check({force: true})
        cy.get('#thursday').check({force: true})
        cy.get('#friday').check({force: true})
        cy.get('#saturday').check({force: true})
        cy.get('#sunday').check({force: true})
        cy.get('#cityId').select("Coatepec")
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#price').type("1")
        cy.get(':nth-child(1) > div > .rounded-sm').type("00:01")
        cy.get('.justify-between > :nth-child(2) > div > .rounded-sm').type("23:59")
        cy.get('.btn-primary').click()
        cy.get('.rounded-md > .text-sm').should("contain.text", "Su nueva tarifa ha sido registrada con éxito")
        cy.get('.shadow-md > .text-lg').should("contain.text", "Coatepec")
        cy.get('.gap-5 > .font-thin').should("contain.text", "Compra de fármacos")
        cy.get('.underline').should("contain.text", "$1 MXN")
    })

    it("Should register a new price rate for services payment", () => {
        cy.get('.bg-yellow-500').click()        
        cy.get('#monday').check({force: true})
        cy.get('#tuesday').check({force: true})
        cy.get('#wednesday').check({force: true})
        cy.get('#thursday').check({force: true})
        cy.get('#friday').check({force: true})
        cy.get('#saturday').check({force: true})
        cy.get('#sunday').check({force: true})
        cy.get('#cityId').select("Coatepec")
        cy.get('#kindOfService').select("Pago de servicios")
        cy.get('#price').type("1")
        cy.get(':nth-child(1) > div > .rounded-sm').type("00:01")
        cy.get('.justify-between > :nth-child(2) > div > .rounded-sm').type("23:59")
        cy.get('.btn-primary').click()
        cy.get('.rounded-md > .text-sm').should("contain.text", "Su nueva tarifa ha sido registrada con éxito")
        cy.get('.shadow-md > .text-lg').should("contain.text", "Coatepec")
        cy.get('.gap-5 > .font-thin').should("contain.text", "Pago de servicios")
        cy.get('.underline').should("contain.text", "$1 MXN")
    })

    it("Should display 'Ya cuenta con una tarifa registrada que tenga los datos introducidos' when trying to register a new price rate that collides with any other previously registered", () => {
        cy.get('.bg-yellow-500').click()        
        cy.get('#monday').check({force: true})
        cy.get('#tuesday').check({force: true})
        cy.get('#wednesday').check({force: true})
        cy.get('#thursday').check({force: true})
        cy.get('#friday').check({force: true})
        cy.get('#saturday').check({force: true})
        cy.get('#sunday').check({force: true})
        cy.get('#cityId').select("Coatepec")
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#price').type("50")
        cy.get(':nth-child(1) > div > .rounded-sm').type("00:01")
        cy.get('.justify-between > :nth-child(2) > div > .rounded-sm').type("23:59")
        cy.get('.btn-primary').click()
        cy.get('.rounded-md > .text-sm').should("contain.text", "Ya cuenta con una tarifa registrada que tenga los datos introducidos")
    })

    // it("Should delete price rate for payment of services", () => {
    //     cy.get(':nth-child(3) > .justify-between > .svg-inline--fa > path').click()
    //     cy.get('.gap-5 > .font-thin').contains("Pago de servicios").should("not.exist")
    // })
})