export {}

describe("New Service Request Tests", () => {
    beforeEach(() => {
        cy.visit("http://localhost:3000")
        cy.get('#emailAddress').type("bipepek652@slvlog.com")
        cy.get('#password').type("AdairBenjamin2008$")
        cy.get('.btn-primary').click()
        cy.get('[href="/providers"] > .flex').click()
    })

    it("Should display 'Sin resultados'", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('#kindOfService').select("Entrega")
        cy.get('#city').select("Coatepec")
        cy.get('.mx-auto > .font-bold').should("contain.text", "Sin resultados")
        // cy.get('#address').select("Av. José Vasconcelos Los manantiales 5").first()
    })

    it("Should find an active price rate", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#city').select("Coatepec")        
        cy.get('form > .text-xl').should("contain.text", "Total: $1 MXN")        
        cy.get('#address').select("Av. José Vasconcelos Los manantiales 5")        
    })

    it("Should register new service request successfully", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#city').select("Coatepec")        
        cy.get('form > .text-xl').should("contain.text", "Total: $1 MXN")        
        cy.get('#address').select("Av. José Vasconcelos Los manantiales 5")
        cy.get('.mx-auto').click()
        cy.get('.font-bold').should("contain.text", "Solicitud de servicio enviada")
    })

    it("Should register a second service request successfully", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#city').select("Coatepec")        
        cy.get('form > .text-xl').should("contain.text", "Total: $1 MXN")        
        cy.get('#address').select("Av. José Vasconcelos Los manantiales 5")
        cy.get('.mx-auto').click()
        cy.get('.font-bold').should("contain.text", "Solicitud de servicio enviada")
    })

    it("Should register a third service request successfully", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#city').select("Coatepec")        
        cy.get('form > .text-xl').should("contain.text", "Total: $1 MXN")        
        cy.get('#address').select("Av. José Vasconcelos Los manantiales 5")
        cy.get('.mx-auto').click()
        cy.get('.font-bold').should("contain.text", "Solicitud de servicio enviada")
    })

    it("Should register a fourth service request successfully", () => {
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#state').select("Veracruz")
        cy.get('#city').select("Coatepec")        
        cy.get('.btn-primary').click()
        cy.get('.flex-grow > .font-bold').click()
        cy.get('.btn-primary').click()
        cy.get('#kindOfService').select("Compra de fármacos")
        cy.get('#city').select("Coatepec")        
        cy.get('form > .text-xl').should("contain.text", "Total: $1 MXN")        
        cy.get('#address').select("Av. José Vasconcelos Los manantiales 5")
        cy.get('.mx-auto').click()
        cy.get('.font-bold').should("contain.text", "Solicitud de servicio enviada")
    })
})